language: c
install: sudo apt-get install libgit2-dev && git clone https://github.com/cktan/tomlc99.git && cd tomlc99 && sudo make install && cd ..
compiler:
  - clang
  - gcc
sudo: false # only for faster builds
script:
  - make
  - ./bin/flotsam
  - gcov ./bin/hello.c
after_success:
  - bash <(curl -s https://codecov.io/bash)

