[package]
name = "flotsam"
type = "bin"
build = "make"
repository = "github.com/briandowns/flotsam"
version = "0.1.0" 
description = "Flotsam is a project generator and dependency manager for C. It's been modeled off of Cargo."
homepage = ""
authors = ["Brian J. Downs"]

[dependencies]
"github.com/briandowns/libspinner.git" = "0.2.0"
